site_name: "LinkML-Transformer"
theme:
#  name: material
  name: windmill
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
  - mknotebooks:
      execute: false
nav:
  - Index: index.md
  - Examples:
      Tutorial: examples/Tutorial.ipynb
  - Specification:
      Data Model: datamodel.md
      Compliance Suite: specification/compliance.md
  - FAQ: faq.md
site_url: https://linkml.github.io/linkml-transformer/
repo_url: https://github.com/linkml/linkml-transformer/
