[tool.poetry]
name = "linkml-map"
version = "0.0.0"
description = "a framework for specifying and executing mappings between data models"
authors = ["cmungall <cjm@berkeleybop.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
asteval = "^0"
click = "^8"
curies = "*"
duckdb = { version = "^0", optional = true }
graphviz = { version = "^0.20.1", optional = true }
jinja2 = "^3"
lark = { version = "^1", optional = true }
linkml-runtime = ">=1.7.2"
pint = { version = "^0", optional = true }
pydantic = ">=2.0.0"
pyyaml = "*"
ucumvert = { version = "^0", optional = true }

[tool.poetry.extras]
duckdb = ["duckdb"]
graphviz = ["graphviz"]
units = ["lark", "pint", "ucumvert"]

[tool.poetry.group.dev.dependencies]
deepdiff = "^6.7.1"
deptry = "^0.21.1"
jupyter = "^1.0.0"
linkml = ">=1.7.0"
mkdocs-mermaid2-plugin = "^0.6.0"
mkdocs-windmill = "*"
mkdocstrings = {extras = ["crystal", "python"], version = "*"}
mknotebooks = "^0.8.0"
pytest = "^7.3.1"
tox = "*"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry.scripts]
linkml-map = "linkml_map.cli.cli:main"

[tool.deptry]
known_first_party = ["linkml_map"]
extend_exclude = ["docs"]

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
reverse_relative = true

# Ref: https://github.com/codespell-project/codespell#using-a-config-file
[tool.codespell]
skip = '.git,*.pdf,*.svg,go.sum,*.lock'
check-hidden = true
ignore-regex = '(^\s*"image/\S+": ".*|\b(KEGG.BRITE|mor.nlm.nih.gov)\b)'
ignore-words-list = 'infarction,amination,assertIn,brite,ehr,mor,brite,nin,mirgate'
