[tool.poetry]
name = "linkml-transformer"
version = "0.1.0"
description = ""
authors = ["cmungall <cjm@berkeleybop.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
linkml-runtime = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
linkml = "^1.3.7"
mkdocs-mermaid2-plugin = "^0.6.0"

[tool.poetry.scripts]
linkml-tr = "linkml_transformer.cli.cli:main"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py39", "py310"]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
reverse_relative = true
